#!/usr/bin/env python3
from pathlib import Path
import re
import shutil
import sys

TOP_NAME = "tt_um_c0d3d1_ldo"
TOP_PINS = "clk ena rst_n ua[0] ua[1] ua[2] ua[3] ua[4] ua[5] ua[6] ua[7]"

infile = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("lvs/tt_um_c0d3d1_ldo_schematic.spice")
outfile = Path(sys.argv[2]) if len(sys.argv) > 2 else infile

if not infile.exists():
    raise SystemExit(f"ERROR: input file not found: {infile}")

text = infile.read_text()
backup = infile.with_suffix(infile.suffix + ".bak")
if outfile == infile:
    shutil.copy2(infile, backup)
    print(f"Backed up original to: {backup}")

lines = text.splitlines()

# Split file into:
# 1. top-level testbench/generated device area before user architecture
# 2. later expanded subckt definitions, especially DEV_OPAMP
top_raw = []
subckt_part = []

in_user_arch = False
after_user_arch = False

for line in lines:
    stripped = line.strip()

    if stripped.startswith("**** begin user architecture code"):
        in_user_arch = True
        continue

    if stripped.startswith("**** end user architecture code"):
        in_user_arch = False
        after_user_arch = True
        continue

    if in_user_arch:
        continue

    # Skip old commented testbench wrapper lines
    if stripped.lower().startswith("**.subckt tb_dev_opamp"):
        continue
    if stripped.lower().startswith("**.ends"):
        continue

    # Everything after the user architecture block is where Xschem expanded DEV_OPAMP
    if after_user_arch:
        subckt_part.append(line)
    else:
        top_raw.append(line)

# Keep only real device instance blocks from the top-level section.
# Need to preserve continuation lines after kept device lines.
remove_prefixes = ("v", "i")  # voltage/current sources should not be in LVS schematic
remove_names = {"c1", "r5"}   # external load cap/resistor from testbench, if present

top_devices = []
keep_continuation = False

for line in top_raw:
    stripped = line.strip()

    if not stripped:
        keep_continuation = False
        continue

    # Skip comments/header
    if stripped.startswith("*"):
        keep_continuation = False
        continue

    # Continuation line belongs to previous kept instance
    if stripped.startswith("+"):
        if keep_continuation:
            top_devices.append(line)
        continue

    first_token = stripped.split()[0]
    low_token = first_token.lower()

    # Remove testbench sources/loads
    if low_token in remove_names or low_token.startswith(remove_prefixes):
        keep_continuation = False
        continue

    # Keep real devices/subckt instances: X..., M..., R..., C...
    # This includes MOSFETs XM..., resistors XR..., BJTs XQ..., opamp x2/x6, MIM caps XC...
    if low_token[0] in ("x", "m", "r", "c"):
        top_devices.append(line)
        keep_continuation = True
    else:
        keep_continuation = False

# Map only the real top-level output net:
# Vout -> ua[0]
# Do NOT map Vdd to ua[1].
def map_top_nets(line: str) -> str:
    line = re.sub(r'(?<![\w\[\]/#])Vout(?![\w\[\]/#])', 'ua[0]', line)
    return line

top_devices = [map_top_nets(l) for l in top_devices]

# Clean subckt part:
# - remove duplicate .GLOBAL/.end temporarily
# - keep DEV_OPAMP as-is, including its internal ua[1] references if you edited it that way
clean_subckt = []
for line in subckt_part:
    stripped = line.strip()
    low = stripped.lower()

    if not stripped:
        clean_subckt.append(line)
        continue

    if low.startswith(".global"):
        continue
    if low == ".end":
        continue

    clean_subckt.append(line)

# Remove accidental old tt_um subckt if present in expanded section
# Simple guard: this script expects raw Xschem-ish file, not already-wrapped file.
if re.search(rf"(?im)^\.subckt\s+{re.escape(TOP_NAME)}\b", "\n".join(clean_subckt)):
    raise SystemExit(
        f"ERROR: {TOP_NAME} subckt already exists in subckt section. "
        "Start from the raw Xschem netlist or remove the old wrapper first."
    )

out = []
out.append(f"* LVS-cleaned schematic netlist generated by make_lvs_schematic.py")
out.append(f"* Source: {infile}")
out.append("")
out.append(f".subckt {TOP_NAME} {TOP_PINS}")
out.extend(top_devices)
out.append(f".ends {TOP_NAME}")
out.append("")
out.extend(clean_subckt)
out.append("")
out.append(".GLOBAL GND")
out.append(".end")
out.append("")

outfile.write_text("\n".join(out))
print(f"Wrote LVS schematic: {outfile}")
print()
print("Subckts now present:")
for line in out:
    if line.lower().startswith(".subckt"):
        print("  " + line)
